# Generated by Django 4.1.2 on 2022-12-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_first_name', models.CharField(max_length=30)),
                ('actor_last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='Actor_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(blank=True, max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ranker.actor')),
            ],
            options={
                'db_table': 'Actor_Movie',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_name', models.CharField(max_length=50)),
                ('rating_meaning', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('box_office_rev', models.FloatField(blank=True, null=True)),
                ('runtime', models.TimeField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, through='movie_ranker.Actor_Movie', to='movie_ranker.actor')),
                ('genre', models.ManyToManyField(blank=True, to='movie_ranker.genre')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_ranker.rating')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.AddField(
            model_name='actor_movie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ranker.movie'),
        ),
    ]
