# Generated by Django 4.1.2 on 2022-12-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ranker', '0002_alter_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
