# Generated by Django 4.1.2 on 2022-12-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ranker', '0003_movie_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor_movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='actor_movie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Actor_Movie',
        ),
    ]
