# Generated by Django 4.1.2 on 2022-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=20)),
                ('box_office_rev', models.FloatField()),
                ('runtime', models.TimeField()),
                ('audience_rating', models.FloatField()),
                ('actors', models.ManyToManyField(blank=True, to='list_movies.actor')),
            ],
        ),
    ]
